# Generated by helper: rename field from completed to resolved
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_task_due_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="completed",
            new_name="resolved",
        ),
    ]
